[[ISSUERS]]
address = "r3ZPN6FALztXp4aFS1Hg4GdJFmmyFQumx9"
name = "PLUTO"

[[ACCOUNTS]]
address = "r3ZPN6FALztXp4aFS1Hg4GdJFmmyFQumx9"
desc = "desc"
domain = "https://plutocoinxrp.netlify.app/"

[[TOKENS]]
issuer = "r3ZPN6FALztXp4aFS1Hg4GdJFmmyFQumx9"
currency = "PLUTO"
name = "PLUTO"
desc = "PLUTO the cat on XRPL. Delusional? Maybe. Pluoto? Definately."
icon = "https://pbs.twimg.com/profile_images/1876903646002069504/V1x-BRJ5_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/plutocoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/plutocoinxrp"
type = "socialmedia"
