[[ISSUERS]]
address = "rNv9vWHXCRM9QgaWkfrAiau3ZxbbeEEb1q"
name = "COSTA"

[[ACCOUNTS]]
address = "rNv9vWHXCRM9QgaWkfrAiau3ZxbbeEEb1q"
desc = "desc"
domain = "https://costacoinxrp.netlify.app/"

[[TOKENS]]
issuer = "rNv9vWHXCRM9QgaWkfrAiau3ZxbbeEEb1q"
currency = "COSTA"
name = "COSTA"
desc = "The Moon is a distraction, Pluto is a planet. Join COSTA as he embarcks on this XRPL journey"
icon = "https://pbs.twimg.com/profile_images/1876743422049976321/j-PaUWNy_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/costacoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/costacoinxrp"
type = "socialmedia"
