[[ISSUERS]]
address = "rshEcEz8twfvtzWEwkbyBzDonkeCjuXKCd"
name = "CHARK"

[[ACCOUNTS]]
address = "rshEcEz8twfvtzWEwkbyBzDonkeCjuXKCd"
desc = "desc"
domain = "https://charkcoinxrp.netlify.app/"

[[TOKENS]]
issuer = "rshEcEz8twfvtzWEwkbyBzDonkeCjuXKCd"
currency = "CHARK"
name = "CHARKOL"
desc = "BORN TO BURN. Burn your doubts and join the hottest $CHARK on the XRP ledger!"
icon = "https://pbs.twimg.com/profile_images/1876459138433044480/V0iptirv_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/charkcoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/charkcoinxrp"
type = "socialmedia"
