[[ISSUERS]]
address = "r9Bx4zmD6F8A2Fr3diqyrHcnRSFFkmVXD5"
name = "COKE"

[[ACCOUNTS]]
address = "r9Bx4zmD6F8A2Fr3diqyrHcnRSFFkmVXD5"
desc = "COKE IT UP"
domain = "zosalncd8lapapu-toml-firstledger-net"

[[TOKENS]]
issuer = "r9Bx4zmD6F8A2Fr3diqyrHcnRSFFkmVXD5"
currency = "COKE"
name = "COKE"
desc = "Welcome to COKE on XRP Ledger. Even your wallet could use a sense of humor"
icon = "https://pbs.twimg.com/profile_images/1442857119460569090/6P3xr19F_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/COKEcoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/COKEcoinxrp"
type = "socialmedia"
