[[ISSUERS]]
address = "rJsDaYHAGS9H7pLdMS8AU8vcsWv75oahwV"
name = "GRIFFIN"

[[ACCOUNTS]]
address = "rJsDaYHAGS9H7pLdMS8AU8vcsWv75oahwV"
desc = "desc"
domain = "https://griffincoinxrp.netlify.app/"

[[TOKENS]]
issuer = "rJht3CmLFHU71c8dwSRt8nw74DkxX3sBMY"
currency = "GRIFFIN"
name = "GRIFFIN"
desc = "Welcome to PeterGriffin on XRP Ledger. Even your wallet could use a sense of humor"
icon = "https://pbs.twimg.com/profile_images/1869052313408507904/gl3_kga9_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/griffincoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/griffincoinxrp"
type = "socialmedia"
