[[ISSUERS]]
address = "rDxdqxDgJxtFMcY8esPgTR2Uzv1rgzMpnu"
name = "SEC"

[[ACCOUNTS]]
address = "rDxdqxDgJxtFMcY8esPgTR2Uzv1rgzMpnu"
desc = "A memeoriablia of the destroyed SEC"
domain = "https://seccoinxrp.netlify.app/"

[[TOKENS]]
issuer = "rDxdqxDgJxtFMcY8esPgTR2Uzv1rgzMpnu"
currency = "SEC"
name = "SEC"
desc = "Welcome to SEC on XRP Ledger. Even your wallet could use a sense of humor"
icon = "https://pbs.twimg.com/profile_images/1900288414240395265/9pismE35_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/seccoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/seccoinxrp"
type = "socialmedia"
