[[ISSUERS]]
address = "rJht3CmLFHU71c8dwSRt8nw74DkxX3sBMY"
name = "DEV"

[[ACCOUNTS]]
address = "rJht3CmLFHU71c8dwSRt8nw74DkxX3sBMY"
desc = "desc"
domain = "https://devcoinxrp.netlify.app/"

[[TOKENS]]
issuer = "rJht3CmLFHU71c8dwSRt8nw74DkxX3sBMY"
currency = "DEV"
name = "DEV"
desc = "The dev is based and cooking for meme season on XRPL"
icon = "https://pbs.twimg.com/profile_images/1868904359972515840/O0SKYKSx_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com/devcoinxrp"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/devcoinxrp"
type = "socialmedia"
